### ISSUE TITLE
Crashes on BottomSheet

### ISSUE THREAD

**Issue by Akshshr** [ZieIony/Carbon#341] opened 2018-05-08 14:55 UTC
Title says it all

Q2: Why isnt there a ripple reveal layout effect? Say from Fragment/Activity to Fragment/Activity

**Comment by ZieIony** [comment] 2018-05-08 17:50
Could you provide more details on the issue you're experiencing? Carbon's BottomSheetLayout was never finished, so I don't think it's usable in its current state.

Please don't ask multiple questions in one issue - that makes issues harder to use for other users looking for solutions. I've created another issue for your second question: #342

**Comment by Akshshr** [comment] 2018-05-30 22:46
Hi there,

Sorry for the late reply, well...I am running a pixel XL on Android 8.

Not sure if I can add more details, just crashes after I click on bottom sheet from the list view

On Tue, May 8, 2018, 7:50 PM ZieIony <notifications@github.com<mailto:notifications@github.com>> wrote:

Could you provide more details on the issue you're experiencing? Carbon's BottomSheetLayout was never finished, so I don't think it's usable in its current state.

Please don't ask multiple questions in one issue - that makes issues harder to use for other users looking for solutions. I've created another issue for your second question: #342<https://github.com/ZieIony/Carbon/issues/342>

**Comment by ZieIony** [comment] 2018-05-31 00:25
Oh, you mean in the sample app. I'll check that.

**Comment by Akshshr** [comment] 2018-05-31 00:32
Bingo!

Thanks


On Thu, May 31, 2018, 2:26 AM ZieIony <notifications@github.com<mailto:notifications@github.com>> wrote:

Oh, you mean in the sample app. I'll check that.

**Comment by ZieIony** [comment] 2018-05-31 15:22
BottomSheet sample works fine for me. Tested on Android 4.1 and 7.0. I don't have access to your device. It would be helpful if I could get the stacktrace from you.

**Comment by Akshshr** [comment] 2018-05-31 15:31
Sure, let me send that over once I have my computer with me

On Thu, May 31, 2018, 5:22 PM ZieIony <notifications@github.com<mailto:notifications@github.com>> wrote:

BottomSheet sample works fine for me. Tested on Android 4.1 and 7.0. I don't have access to your device. It would be helpful if I could get the stacktrace from you.

**Comment by Akshshr** [comment] 2018-06-02 09:06
There we go! 


```
75-22075/tk.zielony.carbonsamples E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: tk.zielony.carbonsamples, PID: 22075
                                                                          java.lang.RuntimeException: Unable to start activity ComponentInfo{tk.zielony.carbonsamples/tk.zielony.carbonsamples.widget.BottomSheetActivity}: java.lang.ClassCastException: tk.zielony.carbonsamples.widget.BottomSheetActivity$onCreate$1 cannot be cast to carbon.widget.DropDown$OnSelectionChangedListener
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2678)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2743)
                                                                              at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1490)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6165)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
                                                                           Caused by: java.lang.ClassCastException: tk.zielony.carbonsamples.widget.BottomSheetActivity$onCreate$1 cannot be cast to carbon.widget.DropDown$OnSelectionChangedListener
                                                                              at tk.zielony.carbonsamples.widget.BottomSheetActivity.onCreate(BottomSheetActivity.kt:22)
                                                                              at android.app.Activity.performCreate(Activity.java:6687)
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2631)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2743) 
                                                                              at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1490) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:154) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6165) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778) 

```

**Comment by ZieIony** [comment] 2018-06-23 15:43
Just an update: I still don't have access to that device (but I should have soon) and I wasn't able to reproduce your issue. The stacktrace doesn't help much.

**Comment by Akshshr** [comment] 2018-07-05 11:03
Keep me posted! :)

**Comment by ZieIony** [comment] 2018-07-06 12:46
I just run that sample on Pixel with Android 8.0 and it's working fine. I'm unable to reproduce your issue and I don't see anything wrong in the code. As I mentioned earlier, Bottom sheet was never finished and in general shouldn't be used anyway. That's why I'm closing this issue.

**Closed as completed by ZieIony** 2018-07-06 12:46 UTC
