### ISSUE TITLE
This feature is implemented using reflection. If you see this exception, something in your setup is not standard.

### ISSUE THREAD

**Issue by M4yankChoudhary** [ZieIony/Carbon#433] opened 2021-12-21 07:23 UTC
- device: Xiaomi Redmi Note 5 Pro, API 28
     - method: carbon.widget.EditText.setCursorColor(...)
     - cause: java.lang.NoSuchFieldException: No field mCursorDrawable in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes2.dex) at getDeclaredField(Class.java:-2)

**Comment by ZieIony** [comment] 2022-04-03 16:50
Duplicate of https://github.com/ZieIony/Carbon/issues/425

**Closed as completed by ZieIony** 2022-04-03 16:50 UTC
