### ISSUE TITLE
AppCompat 22.1+ compatibility thread

### ISSUE THREAD

**Issue by DSteve595** [ZieIony/Carbon#75] opened 2015-04-21 23:42 UTC
With AppCompat 22.0, having a `NoActionBar` theme that just extended one of Carbon's themes was no problem, only `<item name="windowActionBar">false</item>` was needed.

Now, with AppCompat 22.1, `windowActionBar` crashes, as seen [here.](http://stackoverflow.com/questions/29784124/java-lang-illegalargumentexception-appcompat-does-not-support-the-current-theme)

Adding new Carbon themes (`carbon_Theme.AppCompat.Light.NoActionBar` and `carbon_Theme.AppCompat.Dark.NoActionBar`) that extend the AppCompat `NoActionBar` themes should fix this.

**Comment by DSteve595** [comment] 2015-04-21 23:53
As a temporary workaround, I'm making my `NoActionBar` theme extend `AppCompat.NoActionBar`, setting `android:theme` to my custom Carbon theme, and copy-pasting the values (like colorPrimary, colorAccent, etc).

**Comment by ZieIony** [comment] 2015-04-22 16:59
AppCompat 22.1 really changes a lot. Thanks for the issue. If you wish, you can make a pull request. If not, I should be able to fix this tomorrow.

**Comment by DSteve595** [comment] 2015-04-22 17:06
Yeah, looks like lots of changes. If you want to turn this into a general AppCompat 22.1 bug thread, I've also noticed that ImageActionButtons now appear square on 4.4 and below (but are fine on 5.0).
There's also some weirdness happening with a Button of mine inside a drawer, where it's drawing in Holo style on 4.4 and below (but still has Carbon's elevation). The same exact XML placed in a different fragment draws correctly. I'll see if I can make a smaller reproducible situation for you to look at.

**Comment by ZieIony** [comment] 2015-04-22 21:33
Adding the following line seems to do the trick. I will add these 'NoActionBar' themes.

```
<item name="windowNoTitle">true</item>
```

![device-2015-04-22-232635](https://cloud.githubusercontent.com/assets/10180628/7285778/8030ae0c-e947-11e4-8eb6-a22fc5e2a2ef.png)
![device-2015-04-22-232751](https://cloud.githubusercontent.com/assets/10180628/7285779/8032fd9c-e947-11e4-94ea-4f4dc5fb79ec.png)

**Comment by DSteve595** [comment] 2015-04-23 10:31
[Here,](http://developer.android.com/reference/android/view/LayoutInflater.html#setFactory%28android.view.LayoutInflater.Factory%29) this may help with the LayoutInflater Factory issue, which I think is the cause of the action button being square, and possibly a few other things.

**Comment by ZieIony** [comment] 2015-05-03 17:36
I tried to reproduce your issues with ImageActionButton and button on drawer, but with no luck. Could you please make a small project with these issues as you mentioned? Maybe it's a good idea to prepare a public bug project - I'm just thinking.

Seems like there are other libraries having issues with the recent AppCompat - for example Retrolambda

**Comment by DSteve595** [comment] 2015-05-03 17:40
Seems to be fixed in 22.1.1. Not running into the issue anymore. However,
on the ImageActionButton, the ripple drawable seems to disappear
immediately after depressing the button, rather than fading out. Seen on
5.0.

**Comment by ZieIony** [comment] 2015-05-18 20:57
Seems like it's not a good idea to keep all bugs in one thread, because it's hard for me to track them. I keep forgetting about bugs mentioned here. Let's close it and open new issues for all remaining bugs.

**Closed as completed by ZieIony** 2015-05-18 20:57 UTC
Labels: enhancement
