### ISSUE TITLE
implemented using reflection

### ISSUE THREAD

**Issue by shaikhaquib** [ZieIony/Carbon#441] opened 2023-07-18 13:24 UTC
Getting the Following Exception while using Carbon Edittext, Please let us know if we have any solution for it.

This feature is implemented using reflection.

 the following information: 
  - device: Samsung SM-E625F, API 33
  - method: carbon.widget.EditText.setCursorColor(...)
  - cause: java.lang.NoSuchFieldException: No field mCursorDrawable in class Landroid/widget/Editor;
  (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes4.dex) at getDeclaredField(Class.java:-2)
 
 java.lang.NoSuchFieldException: No field mCursorDrawable in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes4.dex)
 	at java.lang.Class.getDeclaredField(Native Method)
 	at carbon.widget.EditText.setCursorColor(EditText.java:346)
 	at carbon.widget.EditText.initEditText(EditText.java:246)
 	at carbon.widget.EditText.<init>(EditText.java:136)
 	at java.lang.reflect.Constructor.newInstance0(Native Method)
 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
 	at android.view.LayoutInflater.createView(LayoutInflater.java:876)
 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1028)
 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:983)
 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1145)
 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1106)
 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1148)
 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1106)
 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1148)
 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1106)
 	at android.view.LayoutInflater.inflate(LayoutInflater.java:692)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:544)

**Comment by ZieIony** [comment] 2023-07-18 20:16
Duplicate of https://github.com/ZieIony/Carbon/issues/424

**Closed as completed by ZieIony** 2023-07-18 20:16 UTC

**Comment by shaikhaquib** [comment] 2023-07-18 21:10
I'm using the latest version, still getting the error, this https://github.com/ZieIony/Carbon/issues/424 does't have any solution  
implementation 'tk.zielony:carbon:0.16.0.1'

**Comment by ZieIony** [comment] 2023-07-20 16:34
#424 says that `0.16.0.1` is not the latest version. The current master HEAD doesn't have the issue you're experiencing, but you have to compile an .apk by yourself or using JitPack.

**Comment by shaikhaquib** [comment] 2023-07-20 20:44
Thanks for the update, i updated the lib to carbon:83060f9cdf does't getting error.

implementation 'com.github.zieiony.Carbon:carbon:83060f9cdf'
