### ISSUE TITLE
Problem with rounded corners

### ISSUE THREAD

**Issue by ali-star** [ZieIony/Carbon#356] opened 2018-08-16 04:31 UTC
![screenshot_20180816-085121](https://user-images.githubusercontent.com/5895322/44187984-0f2f6080-a132-11e8-89d5-10078b424792.png)
when using a layout with rounded corners and child view's with rounded corners too parent layout doesn't clipping child view's with it's corner radius. any help?

**Comment by ZieIony** [comment] 2018-08-16 21:35
I just checked and with stock Android widgets it's fine, so it's clearly a bug in Carbon.

**Comment by ZieIony** [comment] 2018-08-16 22:01
I checked your issue with support CardView and FAB and it seemed to work, but with two CardViews it doesn't work just like in your example. Now I'm not sure if it's a bug in Carbon or actually a limitation in Android implementation. Using software renderer Carbon's rounded corners work fine. Here's a screenshot with two support CardViews:

![image](https://user-images.githubusercontent.com/10180628/44237374-83104e00-a1b0-11e8-82c9-65f5f7f9325d.png)

I'll try to confirm one or another option tomorrow with better examples and using a couple of real devices.

**Comment by ali-star** [comment] 2018-08-17 16:54
for more information, my parent layout is a Framelayout (carbon.widget.Framelayout ) and child layout is a ConstraintLayout (carbon.widget.ConstraintLayout), I hope this Issue will be fixed soon, thank you for support.

**Comment by ZieIony** [comment] 2018-08-17 17:05
Unfortunately, this issue won't be fixed, because it's not Carbon, but Android framework. Today I reproduced your issue using two support CardViews on a clean project and a Samsung phone with Android 7.

If you wish, you can switch these Carbon widgets to software mode by using `view.setRenderingMode(RenderingMode.Software)`. In software mode the clipping works fine.

**Closed as completed** 2018-08-18 16:02 UTC
Labels: bug
