### ISSUE TITLE
Corner radius disappear when creating bitmap for the layout by getDrawingCache()

### ISSUE THREAD

**Issue by eddiecswang** [ZieIony/Carbon#281] opened 2017-04-12 23:14 UTC
I have an image view with carbon corner radius as below and everything works well.

<carbon.widget.ImageView
            android:id="@+id/thumbnail"
            android:layout_width="@dimen/thumbnail_size"
            android:layout_height="@dimen/thumbnail_size"
            app:carbon_cornerRadius="@dimen/thumbnail_radius"/>

But when I tried to getDrawingCache of its parent layout(which is a carbon relative layout), It was not rounded anymore in the bitmap I created with the cache.

Similar behavior with the shared element transition between activities. When the transition starts, the rounded corner will be gone and the image will be square. (rounded image view is not the shared element)

The image view's parent to rootview are all using carbon.

**Comment by ZieIony** [comment] 2017-04-13 08:39
What is the device you're using? Could you prepare a minimal example project with your issue?

**Comment by eddiecswang** [comment] 2017-04-13 15:30
I'm using hTC 10 running Android N. I also tried on Nexus 5X running M. Same results.
I'll setup a sample project soon for testing.

Thank you for the timely response!

**Comment by eddiecswang** [comment] 2017-04-14 18:19
Here's the sample of getting drawing cache from a carbon rounded relative layout.
https://github.com/eddiecswang/CarbonDrawingCacheSample

It contains a relative layout rounded by using carbon radius. When you click on the "Get Cache", it will display the cache bitmap at the bottom.

**Comment by ZieIony** [comment] 2017-04-14 21:53
Thank you very much. I wanted to use exactly your settings just to be sure as I've never experienced your issue. The thing is, I'm using older devices for everyday development and your issue is specific to Android 5.0+. On my Android 4.1 the example worked flawlessly, because it used Carbon's code to draw rounded corners. To make sure, I've replaced Carbon's RecyclerView with a very simple layout, which does pretty much the same:

```
public class TestLayout extends RelativeLayout {
    public TestLayout(Context context, AttributeSet attrs) {
        super(context, attrs);
        setClipToOutline(true);
        setOutlineProvider(new ViewOutlineProvider() {
            @Override
            public void getOutline(View view, Outline outline) {
                outline.setRoundRect(0,0,view.getWidth(), view.getHeight(), 100);
            }
        });
    }
}
```

On Android 5.0 and up Carbon uses a native mechanism (google: _ViewOutlineProvider_) to get the best performance and compatibility on these APIs. View clipping using outlines is hardware accelerated and doesn't work with software drawing. I don't think there's a way to get a fully-drawn, composited image by drawing a view to a bitmap.

Unfortunatelly the problem is wider. The same goes with shadows and circular reveal. This SO post seems to be very close to what you're getting: http://stackoverflow.com/questions/34795786/how-to-capture-screenshot-with-shadow-using-getdrawingcache

I'm not sure about shared element transitions. I imagine that it should work, maybe with a need for another container layout. If not, maybe the transition implementation is somewhat broken.

Your issue is not related to Carbon by any means. In fact, it's caused by the Android's drawing implementation and Carbon can fix that. It's possible to force the backported mode on 5.0+ to get these rounded corners, shadows and other hardware accelerated things on screenshots. I just need a good name for such flag. Carbon already uses such trick to draw colored shadows on 5.0+.

![image](https://cloud.githubusercontent.com/assets/10180628/25057141/9bc8444e-216d-11e7-9372-56e762f35810.png)

**Comment by eddiecswang** [comment] 2017-04-17 15:53
I managed to get an older device for testing and it worked like you said. I should have tried it before posting but thank you for helping finding the cause. 

Like you said, a flag will be nice if there's no side effects or performance issues to force those rounded corder to be on the screenshots. I think for now I'll not use those screenshots for 5.0+.

For the shared element transition I'm guessing it is due to the similar reason since shared element only works on 5.0+ so I couldn't test it on 4.+. Still not a big deal since transition can be done differently.

Thanks again for this awesome library! Let me know if there's anymore information you needed.

**Comment by ZieIony** [comment] 2017-04-17 19:42
No problem. Carbon is supposed to work on all platforms without any differences, so your concern was reasonable. I'll try to add a flag for software rendering mode. It will make things look a tiny bit different and software mode will be slower though.

**Comment by ZieIony** [comment] 2017-04-24 21:42
I've added rendering mode to all widgets with backported hardware-rendering-related features. Rendering mode affects shadows, rounded corners and circular reveal animations. To set rendering mode of a view to software call setRenderingMode(RenderingMode.Software). I didn't have much time to test it, so I don't know if it's production-ready, but if you wish, you can give it a try. I'll test it on your sample and a 5.0+ device soon.

**Comment by eddiecswang** [comment] 2017-04-25 05:29
I can test it around 5.0+ devices soon and will let you know the result. Thanks for the updates!

**Comment by ZieIony** [comment] 2017-07-14 17:54
Today I found a crash, which doesn't allow using RenderingMode.Software on API 21+, so I assume that you didn't check the code. It's fixed now. I'm not happy with quality of software shadows, but RenderingMode works pretty well.

**Closed as completed by ZieIony** 2017-07-14 17:54 UTC
Labels: enhancement
