### ISSUE TITLE
Android 4.4.2 FloatingActionButton Error.

### ISSUE THREAD

**Issue by galibimtiaz** [ZieIony/Carbon#291] opened 2017-04-20 14:05 UTC
```
 E/UncaughtException: android.view.InflateException: Binary XML file line #33: Error inflating class carbon.widget.FloatingActionButton
                                                        at android.view.LayoutInflater.createView(LayoutInflater.java:626)
                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
                                                        at com.twiined.galib.pushlocation.fragments.Map_Fragment_.onCreateView(Map_Fragment_.java:55)
                                                        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                        at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1984)
                                                        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
                                                        at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
                                                        at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
                                                        at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
                                                        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
                                                        at android.view.View.measure(View.java:17327)
                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5363)
                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                        at android.view.View.measure(View.java:17327)
                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5363)
                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                        at android.view.View.measure(View.java:17327)
                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5363)
                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                        at android.view.View.measure(View.java:17327)
                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5363)
                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                        at android.view.View.measure(View.java:17327)
                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5363)
                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                        at android.view.View.measure(View.java:17327)
                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5363)
                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                        at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2548)
                                                        at android.view.View.measure(View.java:17327)
                                                        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2277)
                                                        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1391)
                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1590)
                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1249)
                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6529)
                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:812)
                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:612)
                                                    	at android.view.Choreographer.doFrame(Choreo
```

I have an android tab which runs android 4.4.2 and when ever I try to test my project its crashing with this error.

**Comment by ZieIony** [comment] 2017-04-20 14:17
It doesn't look like it's Carbon as there's nothing related to my code in the stacktrace.

**Comment by galibimtiaz** [comment] 2017-04-20 14:21
Ok I will check again but this time I will remove that floating action button.

**Comment by galibimtiaz** [comment] 2017-04-20 15:11
Not really sure what is wrong , removing the fab and the listener seems to solve the problem. I will close this issue , I will repoen it again if its really from carbon.

**Comment by galibimtiaz** [comment] 2017-04-20 16:37
Ok, Till now what I have found is this error is coming from Floating Action Button src, I think its because I am using vector drawable, Usually android studio suggest to use srcCompact instead of src. Maybe that is the thing causing the problem ? 

Carbon fab is extended from imageView right ? will using AppCompatImageView solve the problem ?

I can use raw svg directly but I am not thinking about me, since this library will be used by many people in future they might not be interested to use svg directly since android studio support vector drawable directly now.

**Comment by ZieIony** [comment] 2017-04-20 19:13
You're right, that was the reason.

I don't want to extend AppCompatImageView due to different approach to widget tinting. Nevertheless, adding app:srcCompat to ImageView is very easy and I did just that.

I don't like adding a new attribute for setting drawables, but I agree that app:srcCompat and VectorDrawables are very popular and some people may find it useful.

**Comment by galibimtiaz** [comment] 2017-04-21 08:13
Getting new errors,

```
E/UncaughtException: java.lang.StackOverflowError
                                                                                     at com.android.internal.util.FastPrintWriter.flushLocked(FastPrintWriter.java:358)
                                                                                     at com.android.internal.util.FastPrintWriter.appendLocked(FastPrintWriter.java:303)
                                                                                     at com.android.internal.util.FastPrintWriter.write(FastPrintWriter.java:625)
                                                                                     at com.android.internal.util.FastPrintWriter.append(FastPrintWriter.java:658)
                                                                                     at java.io.PrintWriter.append(PrintWriter.java:691)
                                                                                     at java.io.PrintWriter.append(PrintWriter.java:31)
                                                                                     at java.lang.Throwable.printStackTrace(Throwable.java:324)
                                                                                     at java.lang.Throwable.printStackTrace(Throwable.java:300)
                                                                                     at android.util.Log.getStackTraceString(Log.java:426)
                                                                                     at android.util.Log.w(Log.java:251)
                                                                                     at carbon.CarbonResources.loadDrawableForCookie(CarbonResources.java:298)
                                                                                     at carbon.CarbonResources.loadDrawable(CarbonResources.java:261)
                                                                                     at carbon.CarbonResources.getDrawable(CarbonResources.java:207)
                                                                                     at carbon.CarbonResources.loadDrawableForCookie(CarbonResources.java:299)
                                                                                     at carbon.CarbonResources.loadDrawable(CarbonResources.java:261)
                                                                                     at carbon.CarbonResources.getDrawable(CarbonResources.java:207)
                                                                                     at carbon.CarbonResources.loadDrawableForCookie(CarbonResources.java:299)
                                                                                     at carbon.CarbonResources.loadDrawable(CarbonResources.java:261)
                                                                                     at carbon.CarbonResources.getDrawable(CarbonResources.java:207)
                                                                                     at carbon.CarbonResources.loadDrawableForCookie(CarbonResources.java:299)
                                                                                     at carbon.CarbonResources.loadDrawable(CarbonResources.java:261)
                                                                                     at carbon.CarbonResources.getDrawable(CarbonResources.java:207)
                                                                                     at carbon.CarbonResources.loadDrawableForCookie(CarbonResources.java:299)
                                                                                     at carbon.CarbonResources.loadDrawable(CarbonResources.java:261)
                                                                                     at carbon.CarbonResources.getDrawable(CarbonResources.java:207)
                                                                                     at carbon.CarbonResources.loadDrawableForCookie(CarbonResources.java:299)
                                                                                     at carbon.CarbonResources.loadDrawable(CarbonResources.java:261)
                                                                                     at carbon.CarbonResources.getDrawable(CarbonResources.java:207)
                                                                                     at carbon.CarbonResources.loadDrawableForCookie(CarbonResources.java:299)
                                                                                     at carbon.CarbonResources.loadDrawable(CarbonResources.java:261)
                                                                                     at carbon.CarbonResources.getDrawable(CarbonResources.java:207)
                                                                                     at carbon.CarbonResources.loadDrawableForCookie(CarbonResources.java:299)
                                                                                     at carbon.CarbonResources.loadDrawable(CarbonResources.java:261)
                                                                                     at carbon.CarbonResources.getDrawable(CarbonResources.java:207)
                                                                                     at carbon.CarbonResources.loadDrawableForCookie(CarbonResources.java:299)
                                                                                     at carbon.CarbonResources.loadDrawable(CarbonResources.java:261)
                                                                                     at carbon.CarbonResources.getDrawable(CarbonResources.java:207)
                                                                                     at carbon.CarbonResources.loadDrawableForCookie(CarbonResources.java:299)
                                                                                     at carbon.CarbonResources.loadDrawable(CarbonResources.java:261)
                                                                                     at carbon.CarbonResources.getDrawable(CarbonResources.java:207)
                                                                                     at carbon.CarbonResources.loadDrawableForCookie(CarbonResources.java:299)
                                                                                     at carbon.CarbonResources.loadDrawable(CarbonResources.java:261)
                                                                                     at carbon.CarbonResources.getDrawable(CarbonResources.java:207)
                                                                                     at carbon.CarbonResources.loadDrawableForCookie(CarbonResources.java:299)
                                                                                     at carbon.CarbonResources.loadDrawable(CarbonResources.java:261)
                                                                                     at carbon.CarbonResources.getDrawable(CarbonResources.java:207)
                                                                                     at carbon.CarbonResources.loadDrawableForCookie(CarbonResources.java:299)
                                                                                     at carbon.CarbonResources.loadDrawable(CarbonResources.java:261)
                                                                                     at carbon.CarbonResources.getDrawable(CarbonResources.java:207)
                                                                                     at carbon.CarbonResources.loadDrawableForCookie(CarbonResources.java:299)
                                                                                     at carbon.CarbonResources.loadDrawable(CarbonResources.java:261)
                                                                                     at carbon.CarbonResources.getDrawable(CarbonResources.java:207)
                                                                                     at carbon.CarbonResources.loadDrawableForCookie(CarbonResources.java:299)
                                                                                     at carbon.CarbonResources.loadDrawable(CarbonResources.java:261)
                                                                                     at carbon.CarbonResources.getDrawable(CarbonResources.java:207)
                                                                                     at carbon.CarbonResources.loadDrawableForCookie(CarbonResources.java:299)
                                                                                     at carbon.CarbonResources.loadDrawable(CarbonResources.java:261)
                                                                                     at carbon.CarbonResources.getDrawable(CarbonResources.java:207)
                                                                                     at carbon.CarbonResources.loadDrawableForCookie(CarbonResources.java:299)
                                                                                 	at carbon.C
04-21 14:10:20.546 8855-8855/com.twiined.galib.pushlocation E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.twiined.galib.pushlocation, PID: 8855
                                                                              java.lang.StackOverflowError
                                                                                  at com.android.internal.util.FastPrintWriter.flushLocked(FastPrintWriter.java:358)
                                                                                  at com.android.internal.util.FastPrintWriter.appendLocked(FastPrintWriter.java:303)
                                                                                  at com.android.internal.util.FastPrintWriter.write(FastPrintWriter.java:625)
                                                                                  at com.android.internal.util.FastPrintWriter.append(FastPrintWriter.java:658)
                                                                                  at java.io.PrintWriter.append(PrintWriter.java:691)
                                                                                  at java.io.PrintWriter.append(PrintWriter.java:31)
                                                                                  at java.lang.Throwable.printStackTrace(Throwable.java:324)
                                                                                  at java.lang.Throwable.printStackTrace(Throwable.java:300)
                                                                                  at android.util.Log.getStackTraceString(Log.java:426)
                                                                                  at android.util.Log.w(Log.java:251)
                                                                                  at carbon.CarbonResources.loadDrawableForCookie(CarbonResources.java:298)
                                                                                  at carbon.CarbonResources.loadDrawable(CarbonResources.java:261)
                                                                                  at carbon.CarbonResources.getDrawable(CarbonResources.java:207)
                                                                                  at carbon.CarbonResources.loadDrawableForCookie(CarbonResources.java:299)
                                                                                  at carbon.CarbonResources.loadDrawable(CarbonResources.java:261)
                                                                                  at carbon.CarbonResources.getDrawable(CarbonResources.java:207)
                                                                                  at carbon.CarbonResources.loadDrawableForCookie(CarbonResources.java:299)
                                                                                  at carbon.CarbonResources.loadDrawable(CarbonResources.java:261)
                                                                                  at carbon.CarbonResources.getDrawable(CarbonResources.java:207)
                                                                                  at carbon.CarbonResources.loadDrawableForCookie(CarbonResources.java:299)
                                                                                  at carbon.CarbonResources.loadDrawable(CarbonResources.java:261)
                                                                                  at carbon.CarbonResources.getDrawable(CarbonResources.java:207)
                                                                                  at carbon.CarbonResources.loadDrawableForCookie(CarbonResources.java:299)
                                                                                  at carbon.CarbonResources.loadDrawable(CarbonResources.java:261)
                                                                                  at carbon.CarbonResources.getDrawable(CarbonResources.java:207)
                                                                                  at carbon.CarbonResources.loadDrawableForCookie(CarbonResources.java:299)
                                                                                  at carbon.CarbonResources.loadDrawable(CarbonResources.java:261)
                                                                                  at carbon.CarbonResources.getDrawable(CarbonResources.java:207)
                                                                                  at carbon.CarbonResources.loadDrawableForCookie(CarbonResources.java:299)
                                                                                  at carbon.CarbonResources.loadDrawable(CarbonResources.java:261)
                                                                                  at carbon.CarbonResources.getDrawable(CarbonResources.java:207)
                                                                                  at carbon.CarbonResources.loadDrawableForCookie(CarbonResources.java:299)
                                                                                  at carbon.CarbonResources.loadDrawable(CarbonResources.java:261)
                                                                                  at carbon.CarbonResources.getDrawable(CarbonResources.java:207)
                                                                                  at carbon.CarbonResources.loadDrawableForCookie(CarbonResources.java:299)
                                                                                  at carbon.CarbonResources.loadDrawable(CarbonResources.java:261)
                                                                                  at carbon.CarbonResources.getDrawable(CarbonResources.java:207)
                                                                                  at carbon.CarbonResources.loadDrawableForCookie(CarbonResources.java:299)
                                                                                  at carbon.CarbonResources.loadDrawable(CarbonResources.java:261)
                                                                                  at carbon.CarbonResources.getDrawable(CarbonResources.java:207)
                                                                                  at carbon.CarbonResources.loadDrawableForCookie(CarbonResources.java:299)
                                                                                  at carbon.CarbonResources.loadDrawable(CarbonResources.java:261)
                                                                                  at carbon.CarbonResources.getDrawable(CarbonResources.java:207)
                                                                                  at carbon.CarbonResources.loadDrawableForCookie(CarbonResources.java:299)
                                                                                  at carbon.CarbonResources.loadDrawable(CarbonResources.java:261)
                                                                                  at carbon.CarbonResources.getDrawable(CarbonResources.java:207)
                                                                                  at carbon.CarbonResources.loadDrawableForCookie(CarbonResources.java:299)
                                                                                  at carbon.CarbonResources.loadDrawable(CarbonResources.java:261)
                                                                                  at carbon.CarbonResources.getDrawable(CarbonResources.java:207)
                                                                                  at carbon.CarbonResources.loadDrawableForCookie(CarbonResources.java:299)
                                                                                  at carbon.CarbonResources.loadDrawable(CarbonResources.java:261)
                                                                                  at carbon.CarbonResources.getDrawable(CarbonResources.java:207)
                                                                                  at carbon.CarbonResources.loadDrawableForCookie(CarbonResources.java:299)
                                                                                  at carbon.CarbonResources.loadDrawable(CarbonResources.java:261)
                                                                                  at carbon.CarbonResources.getDrawable(CarbonResources.java:207)
                                                                                  at carbon.CarbonResources.loadDrawableForCookie(CarbonResources.java:299)
                                                                                  at carbon.CarbonResources.loadDrawable(CarbonResources.java:261)
                                                                                  at carbon.CarbonResources.getDrawable(CarbonResources.java:207)
                                                                              	at carbon.CarbonR
```

**Comment by ZieIony** [comment] 2017-04-21 08:40
What are the steps to reproduce?

**Comment by galibimtiaz** [comment] 2017-04-21 09:02
And also in android 7, hide and show animation is not working. Its just hiding and showing but not animating.

**Comment by ZieIony** [comment] 2017-05-13 23:27
both issues should be fixed now

**Closed as completed by ZieIony** 2017-05-13 23:27 UTC
Labels: enhancement

**Comment by galibimtiaz** [comment] 2017-05-14 09:29
Thank God I have been waiting for this !!!
