### ISSUE TITLE
Android resource compilation failed

### ISSUE THREAD

**Issue by developer--** [ZieIony/Carbon#373] opened 2018-12-27 17:01 UTC
I got this error when trying to add this lib 

Android resource compilation failed
Output: Android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:3066: error: duplicate value for resource 'attr/layout_gravity' with config ''.
Android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:3066: error: resource previously defined here.

Command: /Users/Master/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-osx.jar/cb41f9923ed20baba2a14611d1c177c4/aapt2-3.2.1-4818971-osx/aapt2 compile --legacy \
        -o \
        /Users/Master/Venture-Android/app/build/intermediates/res/merged/debug \
       /app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml
Daemon:  AAPT2 aapt2-3.2.1-4818971-osx Daemon #0

```
`apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

apply plugin: 'kotlin-kapt'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.example.myapp"
        minSdkVersion 17
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = "true"
        multiDexEnabled true

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    dataBinding {
        enabled = true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
````

`dependencies {
   api 'tk.zielony:carbon:0.15.3'
}`

**Comment by ZieIony** [comment] 2018-12-27 18:34
Carbon does not declare `layout_gravity` anywhere, so I would look for the root of this issue somewhere else. Which version of Android Studio and Gradle are you using? Did you try to clean the project? Do you have this project somewhere, so I could investigate this issue more?

**Comment by developer--** [comment] 2018-12-29 12:54
Android studio version => 3.2.1
gradle version => 3.2.1 

Yes, I tried to clean the project, also invalidate cache/restart,  but got the same problem. 

I will try to add this repo to the empty project.

**Comment by sdurovich** [comment] 2019-01-16 08:29
Android Studio 3.3. Gradle tools 3.3.0
Same issue:
Android resource compilation failed
/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:6871: error: duplicate value for resource 'attr/orientation' with config ''.
/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:6871: error: resource previously defined here.

**Comment by ZieIony** [comment] 2019-01-16 10:30
This error seems to be very common on StackOverflow. Carbon doesn't declare 'attr/orientation' anywhere, so I would look for the duplicate in some place else. Maybe there's a conflict in the dependencies?

Could you please prepare a minimal working project showing your issue? I'm unable to reproduce it in my projects.

**Comment by ZieIony** [comment] 2019-01-23 10:05
I'm unable to reproduce this issue and therefore unable to help without any further assistance. Please reopen or comment in case of any change connected the topic.

**Closed as completed by ZieIony** 2019-01-23 10:05 UTC
