### ISSUE TITLE
carbon Layouts problem (like LinearLayout) with  <include />

### ISSUE THREAD

**Issue by ayalma** [ZieIony/Carbon#213] opened 2016-03-14 14:15 UTC
hi .
I'm writing small application with aide of carbon. and my problem is that : when i trying to use `<include/>` in my layout . my application out put don't show any output that related to this included layout . 
this is my code whit carbon : 

```

<?xml version="1.0" encoding="utf-8"?>
<carbon.beta.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    tools:context=".MainActivity">
    <carbon.beta.AppBarLayout
        android:id="@+id/app_bar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:theme="@style/AppTheme.AppBarOverlay">

        <carbon.widget.Toolbar
            android:elevation="@dimen/carbon_elevationToolbar"
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            />

    </carbon.beta.AppBarLayout>

    <carbon.widget.FrameLayout
        android:id="@+id/frameLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">
        <include layout="@layout/item_list" />
    </carbon.widget.FrameLayout>

    <carbon.widget.FloatingActionButton
        android:id="@+id/fab"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom|end"
        android:layout_margin="@dimen/fab_margin"
        android:src="@android:drawable/ic_dialog_email" />
 </carbon.beta.CoordinatorLayout>
```

and blank screen is my output .
and by changing FrameLayout to android's FrameLayout problem going away .

```
<?xml version="1.0" encoding="utf-8"?>
<carbon.beta.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    tools:context=".MainActivity">
    <carbon.beta.AppBarLayout
        android:id="@+id/app_bar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:theme="@style/AppTheme.AppBarOverlay">

        <carbon.widget.Toolbar
            android:elevation="@dimen/carbon_elevationToolbar"
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            />

    </carbon.beta.AppBarLayout>

    <FrameLayout
        android:id="@+id/frameLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">
        <include layout="@layout/item_list" />
    </FrameLayout>

    <carbon.widget.FloatingActionButton
        android:id="@+id/fab"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom|end"
        android:layout_margin="@dimen/fab_margin"
        android:src="@android:drawable/ic_dialog_email" />
 </carbon.beta.CoordinatorLayout>
```

**Comment by rhonyabdullah** [comment] 2016-03-16 23:24
Is this issue can be fixed by using carbon ?
By the way, using Framelayout, linearlayout or relativelayout for including layout didn't show shadow carbon widget.

**Comment by ZieIony** [comment] 2016-03-19 01:07
This issue was caused by broken PercentLayoutHelper. Fixed

@rhonyabdullah only Carbon layouts can draw shadows on all api levels. You have to use them to get shadows for your widgets.

**Closed as completed by ZieIony** 2016-03-19 01:07 UTC
