### ISSUE TITLE
OnItemClickListener in ListView

### ISSUE THREAD

**Issue by n3vr0s** [ZieIony/Carbon#51] opened 2015-03-17 15:38 UTC
I'm trying to add OnItemClickListener for carbon.widget.ListView and my callback does not work.
Also I have tried adding OnClickListener on View which is inflated in adapter with no success. ( Root element of inflated view is carbon.widget.CardView )
How can I add callback after click on list item and have ripple effect on item?

**Comment by ZieIony** [comment] 2015-03-17 17:10
carbon.widget.ListView doesn't change anything related to touch events, so OnItemClickListener and onClickListener should work fine. The issue is that carbon.widget.CardView has clickable attribute set on it's content. See:

https://github.com/ZieIony/Carbon/blob/master/carbon/src/main/res/layout/carbon_cardview.xml#L9

As you can see, CardView is really just a layout. To workaround this issue you can simply copy that layout to your code and remove the clickable attribute.

**Comment by ZieIony** [comment] 2015-03-17 17:11
I'm marking this as a bug. carbon.widget.CardView was created only to showcase the RippleDrawable and shadows with cards and RecyclerView. Seems like there's a need for such component, so I'm going to update the CardView class to make it more usable.

**Comment by ZieIony** [comment] 2015-03-24 23:26
CardView was updated in 0.7.0. Check RecyclerView & cards sample for details. Setting click listeners should work fine now.

**Closed as completed by ZieIony** 2015-03-24 23:26 UTC
Labels: bug
