### ISSUE TITLE
EditText - method: carbon.widget.EditText.setCursorColor(...)

### ISSUE THREAD

**Issue by sushilGlocify** [ZieIony/Carbon#440] opened 2023-04-27 05:54 UTC
Hi, I don' t know why I keep getting this error in Edit Text Only, Here Is my Log

**```
E/Carbon: This feature is implemented using reflection. If you see this exception, something in your setup is not standard. Please create an issue on https://github.com/ZieIony/Carbon/issues. Please provide at least the following information: 
     - device: Xiaomi Mi A2, API 29
     - method: carbon.widget.EditText.setCursorColor(...)
     - cause: java.lang.NoSuchFieldException: No field mCursorDrawable in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes3.dex) at getDeclaredField(Class.java:-2)
    
    java.lang.NoSuchFieldException: No field mCursorDrawable in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes3.dex)
        at java.lang.Class.getDeclaredField(Native Method)
        at carbon.widget.EditText.setCursorColor(EditText.java:346)
        at carbon.widget.EditText.initEditText(EditText.java:246)
        at carbon.widget.EditText.<init>(EditText.java:136)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at com.templeBliss.databinding.FragmentEditProfileBinding.inflate(FragmentEditProfileBinding.java:98)
        at com.templeBliss.ui.customer.fragments.editProfile.EditProfileFragment.onCreateView(EditProfileFragment.kt:24)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1823)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7403)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```**

**Comment by shaikhaquib** [comment] 2023-07-18 13:28
Hello
Did you find any solution for it?

**Comment by ZieIony** [comment] 2023-07-18 20:16
Duplicate of https://github.com/ZieIony/Carbon/issues/424

**Closed as completed by ZieIony** 2023-07-18 20:16 UTC
