### ISSUE TITLE
Crashed when using FrameLayout with fragment have SwipeRefreshLayout

### ISSUE THREAD

**Issue by namkazt** [ZieIony/Carbon#392] opened 2019-09-24 04:00 UTC
When application initializes and you quickly swipe or touch the screen it will crash.

Error Log:
```
E/InputEventReceiver: Exception dispatching input event.
E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI: java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
        at android.view.ViewGroup.getAndVerifyPreorderedView(ViewGroup.java:3061)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2234)
        at carbon.widget.FrameLayout.dispatchTouchEvent(FrameLayout.java:462)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
```

Main Activity:
```
<layout xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools"
        xmlns:app="http://schemas.android.com/apk/res-auto">
    <data>

    </data>
    <FrameLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent" android:id="@+id/fragment_container"/>
</layout>
```

and Fragment has: 
```
<androidx.swiperefreshlayout.widget.SwipeRefreshLayout
                android:id="@+id/swipe_refresh_container"
                android:layout_width="0dp"
                android:layout_height="0dp"
                app:layout_constraintTop_toBottomOf="@+id/line"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintBottom_toBottomOf="parent"
                android:layout_marginTop="8dp">

            <androidx.recyclerview.widget.RecyclerView
                    android:id="@+id/product_recycler_view"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    tools:listitem="@layout/row_campaign" />

        </androidx.swiperefreshlayout.widget.SwipeRefreshLayout>
```

It does not happen when I use `androidx...FrameLayout`

**Comment by ZieIony** [comment] 2019-09-24 13:11
This may be related to child drawing order. I'll try to reproduce your issue. Can you share your device's model and Android version?

**Comment by namkazt** [comment] 2019-09-25 01:43
Android 7.1.2 
Device: SM-T561

it happens when I use `carbon.widget.FrameLayout` in main activity instead of `FrameLayout` and when it initializing ( fragment not fully display yet ) you try to swipe fast it will crash

**Comment by ZieIony** [comment] 2019-10-01 22:41
I tried to reproduce your issue, but with no luck. This looks like a race condition related to child drawing order, but I don't see how it could happen.

I don't know what do you mean by "fragment not fully display yet". I created an Activity and a Fragment with the layouts you provided, but for me the Fragment instantiates and works correctly.

Could you prepare a minimal reproducible sample of your issue for me? A project on GitHub would be perfect. An app demonstrating your issue (crashing for you), that I could download and debug.

Please make sure that you're using the most recent version of Carbon. I'm currently working on a couple of new things. I don't think that I changed anything in view ordering, but who knows.

**Comment by namkazt** [comment] 2019-10-02 01:30
@ZieIony I mean when fragment is `onCreateView` stage that not displaying anything yet but a white screen, then I try to swipe on the screen ( on the part that should be displayed FrameLayout )

NOTE: I'm not tested with the new version of Carbon yet ( i just updated it after use androidx.FrameLayout ). I will test again and inform you about it.

**Comment by ZieIony** [comment] 2019-10-02 16:57
When fragment is in 'onCreateView', its view is not yet available for the container, so the code should behave like it was empty. Adding a fragment is very fast and stable operation, so I believe that there's more than just adding a fragment to cause this issue. That's why I asked about a an example project showing your issue.

**Comment by ZieIony** [comment] 2019-10-11 13:18
I'm unable to reproduce this crash. I'm closing the issue. Please reopen if needed.

**Closed as completed by ZieIony** 2019-10-11 13:18 UTC
