### ISSUE TITLE
E/Carbon: This feature is implemented using reflection

### ISSUE THREAD

**Issue by PriyankaOCD** [ZieIony/Carbon#424] opened 2021-01-19 12:48 UTC
- device: HUAWEI AQM-LX1, API 29
- method: carbon.widget.EditText.setCursorColor(...)
- cause: java.lang.NoSuchFieldException: No field mCursorDrawable in class Lhuawei/com/android/internal/widget/HwEditor; (declaration of 'huawei.com.android.internal.widget.HwEditor' appears in /system/framework/hwEmui.jar) at getDeclaredField(Class.java:-2)

**Comment by ZieIony** [comment] 2021-01-19 18:37
Which version are you using? Did you try the current master via JitPack? This code is no longer present in the library.

**Comment by devabir93** [comment] 2021-02-15 14:56
i am using the latest version 0.16.0.1 and still get the same error

**Comment by ZieIony** [comment] 2021-02-15 19:50
This is a duplicate of #326. This code was removed a long time ago and is no longer present in the library. Version 0.17.0 was never released, but you can build the current master via JitPack and get all the fixes this way.

**Comment by PriyankaOCD** [comment] 2021-02-16 05:41
I am using version -

api 'tk.zielony:carbon:0.16.0.1'

**Comment by PriyankaOCD** [comment] 2021-02-16 05:43
> Which version are you using? Did you try the current master via JitPack? This code is no longer present in the library.

I am using version -

api 'tk.zielony:carbon:0.16.0.1'

**Comment by PriyankaOCD** [comment] 2021-02-16 05:48
> This is a duplicate of #326. This code was removed a long time ago and is no longer present in the library. Version 0.17.0 was never released, but you can build the current master via JitPack and get all the fixes this way.

Thank you for your prompt responses. Kindly guide me with this

So in my app level build.gradle 
api 'tk.zielony:carbon:0.16.0.1' -> to which version should I change this to

**Comment by ZieIony** [comment] 2021-02-16 10:58
You can find instructions here: https://jitpack.io/#zieiony/Carbon/83060f9cdf

You can also build Carbon by yourself, by cloning the repository and building an archive using Android Studio.

**Closed as completed** 2021-02-23 17:09 UTC
