### ISSUE TITLE
RecyclerView swiping Error

### ISSUE THREAD

**Issue by amSaadatmand** [ZieIony/Carbon#334] opened 2018-01-29 05:24 UTC
The items inside the RecyclerView will be error when swiping...

`FATAL EXCEPTION: main
Process: tk.zielony.carbonsamples, PID: 19850
java.lang.NullPointerException: Attempt to get length of null array`

Please watch this movie. My Android device is version 7.1.
[https://vimeo.com/253194519](https://vimeo.com/253194519)

**Comment by ZieIony** [comment] 2018-02-14 13:07
duplicate of #333

**Closed as completed by ZieIony** 2018-02-14 13:07 UTC
