### ISSUE TITLE
EditText and CheckBox colors

### ISSUE THREAD

**Issue by NamtarR** [ZieIony/Carbon#164] opened 2015-12-18 04:32 UTC
Hi! I am developing an app using Carbon library and now I'm stuck on a simple issue. I can't make EditText and CheckBox colors to be different in different states. I want an EditText to have, let's say, a green divider while I'm typing text and a gray one when the EditText loses focus. Now I can make it be green always or gray always. The same with CheckBox - I need it to have gray borders when unchecked but green fill when checked but all I can do is white borders with green fill. I have seen a behavior I need in a sample app but somehow I can't manage to get it to work in mine. Color selector with different states are of no help so can you please help me with such an issue?

**Comment by ZieIony** [comment] 2015-12-18 09:59
Could you please post some code? Both CheckBox and EditText use selectors, so it should work no problem. The attribute is called tint.

**Comment by NamtarR** [comment] 2015-12-21 04:57
Here is the checkbox:

``` xml
<carbon.widget.CheckBox
                android:id="@+id/coordinates_check"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_below="@id/description_field"
                android:layout_marginLeft="16dp"
                android:layout_marginTop="24dp"
                android:checked="false"
                android:drawablePadding="16dp"
                android:paddingLeft="0dp"
                android:text="@string/activity_add_check_coordinates"
                android:textAllCaps="true"
                android:textColor="@color/stone_normal"
                android:textSize="14sp"
                app:carbon_fontPath="Roboto-Medium.ttf"
                app:carbon_tint="@drawable/checkbox_color" />
```

And here is the selector:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:color="@color/carrot_normal" android:state_checked="true" />
    <item android:color="@color/stone_normal" />
</selector>
```

I have tried almost all states in selector but nothing seemed to work. The only solution I have found so far is to change the theme of that particular activity containing checkbox and include colorControlNormal and colorControlHighlight colors like that:

``` xml
<style name="AppTheme.AddActivity" parent="AppTheme">
        <item name="colorControlNormal">@color/stone_normal</item>
        <item name="android:colorControlHighlight">@color/stone_normal</item>
        <item name="android:statusBarColor">@color/spring_dark</item>
    </style>
```

Now my checkbox has gray borders while unchecked and accent color fill while checked. I've managed to reach necessary behavior but it seems a bit wrong way for me.

**Comment by ZieIony** [comment] 2015-12-21 10:00
Impressive bug report, thanks. I did some checks and now I can confirm - it's a bug in tint selectors.

https://github.com/ZieIony/Carbon/blob/master/carbon/src/main/java/carbon/Carbon.java#L111

This line should fail in case the provided resource is a reference, but apparently such attribute is being interpreter as an int and used as a color. It means that the bug is wider than we thought and affects all selectors used in Carbon.

It should be fixed today.

And if you wonder why such thing could slip through tests - I'm not using xml selectors, because Android older than 5.0 doesn't support nested references in resources. It means that I can't use Theme colors in xml selectors, which is crucial in Material Design controls.

**Comment by NamtarR** [comment] 2015-12-21 10:12
I am very glad I could help. Concerning the use of selectors: why not use common color references? I can't imagine any other way of setting colorStateList except xml selectors or setColor(ColorStateList list) methods. If you have a better solution, please tell me, it is quite interesting.

**Comment by ZieIony** [comment] 2015-12-21 14:11
I'm using setColor(ColorStateList) with ColorStateList constructed in code. Like this:

https://github.com/ZieIony/Carbon/blob/master/carbon/src/main/java/carbon/drawable/ControlCheckedColorStateList.java

It's not new, nor elegant, but has one advantage against xml selectors - correctly resolves theme references. Compare these three pieces of code:

```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:color="#ff0000" android:state_checked="true" />
    <item android:color="#000000"  />
</selector>
```

```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:color="@color/red" android:state_checked="true" />
    <item android:color="@color/black"  />
</selector>
```

```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:color="?attr/colorControlChecked" android:state_checked="true" />
    <item android:color="?attr/colorControlNormal"  />
</selector>
```

First one has colors provided as direct values. Second one has colors provided by reference to static resource. These references can be resolved and inlined at compile time.

Third one is different. Colors in the third xml are dynamic references dependent on the current theme. These references don't work on Android KitKat and below. These references are key to Material Design one-color-style idea. On older platforms these references will be interpreted as integer constants and used as direct color values.

Google fixed that by adding TintManager:

http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/5.0.1_r1/android/support/v7/internal/widget/TintManager.java

For now I'm using something similar, but less generic. Maybe I should try to copy their code.

**Comment by ZieIony** [comment] 2015-12-22 00:15
Fixed

**Closed as completed by ZieIony** 2015-12-22 00:15 UTC
Labels: bug
