### ISSUE TITLE
flat button has shadow

### ISSUE THREAD

**Issue by ishowrunes** [ZieIony/Carbon#161] opened 2015-12-11 11:45 UTC
I have added 0dp elevation and added "style="@style/carbon_Button.Flat" to the button. The shadow is still present.

**Comment by ZieIony** [comment] 2015-12-12 08:23
could you please post your xml with that buton?

**Comment by ishowrunes** [comment] 2015-12-14 04:57
```
<LinearLayout
        android:id="@+id/llRangeControls"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="end"
        android:orientation="horizontal"
        android:padding="@dimen/globalPadding">

        <carbon.widget.Button
            android:id="@+id/btnCancel"
            style="@style/carbon_Button.Flat"
            android:layout_width="wrap_content"
            android:layout_height="@dimen/buttonHeight"
            android:layout_gravity="end"
            android:layout_marginBottom="@dimen/cardPadding"
            android:layout_marginLeft="@dimen/cardPadding"
            android:layout_marginRight="@dimen/cardPadding"
            android:text="@string/button_cancel"
            android:textColor="@color/danger"
            app:carbon_cornerRadius="@dimen/raisedBtnRadius"
            app:carbon_elevation="0dp"
            app:carbon_rippleColor="@color/defaultRipple" />

        <carbon.widget.Button
            android:id="@+id/btnAdd"
            style="@style/carbon_Button.Flat"
            android:layout_width="wrap_content"
            android:layout_height="@dimen/buttonHeight"
            android:layout_gravity="end"
            android:layout_marginBottom="@dimen/cardPadding"
            android:layout_marginLeft="@dimen/cardPadding"
            android:layout_marginRight="@dimen/cardPadding"
            android:text="@string/button_add"
            android:textColor="@color/primary"
            app:carbon_cornerRadius="@dimen/raisedBtnRadius"
            app:carbon_elevation="0dp"
            app:carbon_rippleColor="@color/defaultRipple" />

    </LinearLayout>
```

[Layout Image](http://i.imgur.com/i065Seu.png?1)

I am using the flat buttons in a custom dialog.

**Comment by ZieIony** [comment] 2015-12-14 09:42
Carbon draws shadows in parent layouts and you're using plain LinearLayout instead of carbon.widget.LinearLayout. That's why it may be unrelated to Carbon. I would suggest you to create a simple, clean project, add a minimal set of libraries, copy that layout to the new project and check if it's working.

This is how your layout looks in a clean project created by me 5 minutes ago:

![device-2015-12-14-103922](https://cloud.githubusercontent.com/assets/10180628/11777484/11d7b3da-a24f-11e5-9264-f934f6aa08a3.png)

**Comment by ZieIony** [comment] 2015-12-22 00:15
No answer for 7 days, I'm unable to reproduce the issue, closing.

**Closed as completed by ZieIony** 2015-12-22 00:15 UTC
