### ISSUE TITLE
svg problem with ImageView and FloatingActionButton

### ISSUE THREAD

**Issue by FunnyDevs** [ZieIony/Carbon#133] opened 2015-09-01 19:30 UTC
When i use src attribute with svg resource (inside raw folder) there is no resource loading. It work's only with png value. I use Android 4.1

**Comment by ZieIony** [comment] 2015-09-01 20:41
Please make sure that:
- you're using the most recent version of Carbon (0.10.1),
- you're using carbon.widget.ImageView/FloatingActionButton, not android.widget.ImageView/FloatingActionButton,
- you're referencing @raw/res, not @drawable/res,
- your svgs are correct and can be loaded using other methods (carbon.drawable.VectorDrawable),
- you're using a colored svg or a filter which actually can be seen,
- your widgets have correct size.

Also, compare your code to the sample code (R.layout.activity_svg).

What is the result you're getting?

**Comment by FunnyDevs** [comment] 2015-09-01 20:46
Yes, i use the version 0.10.1
I tried with one of your svg file. In fact this is my xml widget code

```
        <carbon.widget.FloatingActionButton
        android:layout_width="@dimen/carbon_fabSize"
        android:layout_height="@dimen/carbon_fabSize"
        android:layout_margin="@dimen/carbon_padding"
        android:layout_alignParentRight="true"
        android:layout_alignParentBottom="true"
        android:background="?colorPrimary"
        android:src="@raw/ic_face_24px" />
```

**Comment by ZieIony** [comment] 2015-09-02 08:56
It's working for me no problem, so let's go with more questions:

Does your app work on other phones? Does the Carbon sample app work on your phone?

What is the result you see? A single-color FAB with no icon? No FAB at all?

Did you try to download Carbon sources and debug the loading process?

Could you try to reproduce the issue using the smallest working part of your code? An Activity with a single layout containing that FAB.

**Comment by FunnyDevs** [comment] 2015-09-02 17:21
I'm trying a new project with only one activity and the FAB works with svg loaded!  
But the problem is in my production app: the result is a single-color Fab with no icon. I have tried to rebuild the problem but nothing is changed.

**Comment by FunnyDevs** [comment] 2015-09-02 17:50
I'm trying in another Activity of my project and same result. I don't know what blocks the loading of svg files!

**Comment by FunnyDevs** [comment] 2015-09-02 19:24
I found, debugging, which part is the problem: In ImageView

```
        if (getDrawable() == null && ((resId & 0xffff0000) == 0x7f050000))
            setImageDrawable(new VectorDrawable(getResources(), resId));
```

The If statement always fails! When i comment the If statement the system loads the svg file! 
According to you, which is now the problem????

**Comment by ZieIony** [comment] 2015-09-02 20:52
There are two possibilities:
1. The getDrawable() method returned null, which is very unlikely.
2. The resId variable doesn't match the raw resource pattern. It's either an issue with resource id or resId==0 due to an issue with src attribute.

Could you please check what is the value returned by getDrawable() and what is the value of resId.

**Comment by FunnyDevs** [comment] 2015-09-02 21:09
getDrawable returns null and resid = 2131099661

**Comment by ZieIony** [comment] 2015-09-02 21:41
Ok, so this is the problem. Thank you very much for your debugging work. That resId is equal to 7F06000D in hex - it doesn't match the raw resource pattern. I don't know why, maybe something related to resource generation has changed.

It's a bug in Carbon - resource resolving shouldn't be affected by SDK version.

For now you can set that icon from code, update the pattern, comment out the line or just use pngs.

**Comment by FunnyDevs** [comment] 2015-09-02 21:45
Ok, thanks a lot. I'll set the icon from code

**Comment by NeverGivinUp** [comment] 2015-09-13 23:38
I have the same problem. All my raw images are in the 0x7f06xxxx range, since I updated to SDK Build Tools 23.0.0

**Comment by NeverGivinUp** [comment] 2015-09-14 07:17
Resource#getResourceTypeName returns the type name if a resource id: drawable, array, string, raw, color, layout, etc..

I think if you'd replace in ImageView.java the line 

``` java
 if (getDrawable() == null && ((resId & 0xffff0000) == 0x7f050000))
```

by 

``` java
 if (getDrawable() == null &&  getContext().getResources().getResourceTypeName(resId).equals("raw"))
```

it would be stable against changing SDK versions.

**Comment by ZieIony** [comment] 2015-09-18 07:38
Yup, that should solve the issue. It should be ready next week (I'm pretty much offline till then, sorry)

**Comment by ZieIony** [comment] 2015-09-21 20:05
Fixed using your suggestion. Thank you very much!

**Closed as completed by ZieIony** 2015-09-21 20:05 UTC
Labels: bug, help wanted
