### ISSUE TITLE
java.lang.NoSuchFieldException: No field mCursorDrawable in class Landroid/widget/Editor;

### ISSUE THREAD

**Issue by milinocean** [ZieIony/Carbon#421] opened 2020-10-04 11:35 UTC
Carbon: This feature is implemented using reflection. If you see this exception, something in your setup is not standard.

     - device: samsung SM-M307F, API 29
     - method: carbon.widget.EditText.setCursorColor(...)
     - cause: java.lang.NoSuchFieldException: No field mCursorDrawable in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes3.dex) at getDeclaredField(Class.java:-2)
    
    java.lang.NoSuchFieldException: No field mCursorDrawable in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes3.dex)

**Comment by ZieIony** [comment] 2020-10-04 15:02
Duplicate of #415 . Please update the library to get rid of this issue.

**Closed as completed by ZieIony** 2020-10-04 15:02 UTC
