### ISSUE TITLE
No Field mCursorDrawable in class Landroid/widget/Editor

### ISSUE THREAD

**Issue by kangkosw** [ZieIony/Carbon#415] opened 2020-07-14 07:32 UTC
E/Carbon: This feature is implemented using reflection. If you see this exception, something in your setup is not standard. Please create an issue on https://github.com/ZieIony/Carbon/issues. Please provide at least the following information: 
     - device: Google AOSP on IA Emulator, API 28
     - method: carbon.widget.EditText.setCursorColor(...)
     - cause: java.lang.NoSuchFieldException: No field mCursorDrawable in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes2.dex) at getDeclaredField(Class.java:-2)
    
    java.lang.NoSuchFieldException: No field mCursorDrawable in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes2.dex)
        at java.lang.Class.getDeclaredField(Native Method)
        at carbon.widget.EditText.setCursorColor(EditText.java:346)
        at carbon.widget.EditText.initEditText(EditText.java:246)
        at carbon.widget.EditText.<init>(EditText.java:136)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
        at com.mobile.hin.modules.sig_in.SignInActivity.onCreate(SignInActivity.kt:32)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
W/com.mobile.hin: Accessing hidden field Landroid/widget/Editor;->mIgnoreActionUpEvent:Z (dark greylist, reflection)
D/EGL_emulation: eglMakeCurrent: 0xe6185900: ver 3 0 (tinfo 0xcfcf0250)
D/EGL_emulation: eglMakeCurrent: 0xe6185900: ver 3 0 (tinfo 0xcfcf0250)
D/EGL_emulation: eglMakeCurrent: 0xe6185900: ver 3 0 (tinfo 0xcfcf0250)
I/chatty: uid=10096(com.mobile.hin) RenderThread identical 3 lines
D/EGL_emulation: eglMakeCurrent: 0xe6185900: ver 3 0 (tinfo 0xcfcf0250)

**Comment by ZieIony** [comment] 2020-07-14 19:03
In the most recent version `EditText::setCursorColor(int)` is deprecated and doesn't do anything.

**Comment by ZieIony** [comment] 2020-07-14 19:04
Duplicate of #326

**Closed as completed by ZieIony** 2020-07-14 19:04 UTC
Labels: bug
